spring.datasource.url=jdbc:postgresql://localhost:5432/pl_data
spring.datasource.username=postgres
spring.datasource.password=Summer11$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

football.api.base-url=${FOOTBALL_API_BASE_URL:https://v3.football.api-sports.io}
football.api.key=${FOOTBALL_API_KEY:}

server.port=9090
